# Generated by Django 6.0 on 2026-01-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='observation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
    ]
