# Generated by Django 6.0 on 2026-01-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('reserved', 'Reserved'), ('completed', 'Completed'), ('no_show', 'No Show')], default='canceled', max_length=20),
        ),
    ]
